service: serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

package:
  excludeDevDependencies: true
  individually: true
  
plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  hello:
    handler: src/functions/hello.handler
    events:
     - http:
         path: /test
         method: get